//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculateFinalRoundFixtures_Lightning
    {
        public Nullable<int> CompID { get; set; }
        public int TimeSlot { get; set; }
        public int Diamond { get; set; }
        public int Game { get; set; }
        public int HomeTeamID { get; set; }
        public int AwayTeamID { get; set; }
    }
}
