//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompFixtureTemplate
    {
        public int CompTypeID { get; set; }
        public int NumberOfTeams { get; set; }
        public int GameNumber { get; set; }
        public int DiamondNumber { get; set; }
        public int HomeTeamRank { get; set; }
        public int AwayTeamRank { get; set; }
        public string MatchCode { get; set; }
        public string HomeTeamMatchCode { get; set; }
        public string HomeTeamWinLoss { get; set; }
        public string AwayTeamMatchCode { get; set; }
        public string AwayTeamWinLoss { get; set; }
    
        public virtual CompType CompType { get; set; }
    }
}
