//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comp()
        {
            this.CompClubs = new HashSet<CompClub>();
            this.CompDates = new HashSet<CompDate>();
            this.CompDiamonds = new HashSet<CompDiamond>();
            this.CompFixtures = new HashSet<CompFixture>();
            this.CompTeams = new HashSet<CompTeam>();
        }
    
        public int CompID { get; set; }
        public string CompName { get; set; }
        public int CompTypeID { get; set; }
        public int HostClubID { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Comp Comp1 { get; set; }
        public virtual Comp Comp2 { get; set; }
        public virtual CompType CompType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompClub> CompClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompDate> CompDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompDiamond> CompDiamonds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompFixture> CompFixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompTeam> CompTeams { get; set; }
    }
}
