//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompTeam()
        {
            this.CompFixtures = new HashSet<CompFixture>();
            this.CompFixtures1 = new HashSet<CompFixture>();
        }
    
        public int CompTeamID { get; set; }
        public int CompID { get; set; }
        public int CompClubID { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public string GroupName { get; set; }
        public string Division { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Comp Comp { get; set; }
        public virtual CompClub CompClub { get; set; }
        public virtual CompDivision CompDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompFixture> CompFixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompFixture> CompFixtures1 { get; set; }
        public virtual CompGroup CompGroup { get; set; }
    }
}
