//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompDiamondAllocation
    {
        public int CompID { get; set; }
        public string GroupName { get; set; }
        public string Division { get; set; }
        public int DiamondNumber { get; set; }
        public int GameNumber { get; set; }
        public int TimeSlot { get; set; }
        public int Diamond { get; set; }
    
        public virtual CompDivision CompDivision { get; set; }
        public virtual CompTimeSlot CompTimeSlot { get; set; }
    }
}
