//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompTimeSlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompTimeSlot()
        {
            this.CompDiamondAllocations = new HashSet<CompDiamondAllocation>();
            this.CompFixtures = new HashSet<CompFixture>();
            this.CompUmpireAllocations = new HashSet<CompUmpireAllocation>();
        }
    
        public int CompID { get; set; }
        public int TimeSlot { get; set; }
        public System.DateTime Date { get; set; }
        public int Day { get; set; }
        public int TimeSlotInDay { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual CompDate CompDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompDiamondAllocation> CompDiamondAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompFixture> CompFixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompUmpireAllocation> CompUmpireAllocations { get; set; }
    }
}
