//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliation
    {
        public int ClubId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime AffiliationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> NumberOfTeams { get; set; }
        public Nullable<int> NumberOfPlayers { get; set; }
        public Nullable<int> NumberOfVolunteers { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Person Person { get; set; }
    }
}
