//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tbawaEntities : DbContext
    {
        public tbawaEntities()
            : base("name=tbawaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affiliation> Affiliations { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<ClubContact> ClubContacts { get; set; }
        public virtual DbSet<OfficeBearer> OfficeBearers { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<ClubRolePerson> ClubRolePersons { get; set; }
        public virtual DbSet<Comp> Comps { get; set; }
        public virtual DbSet<CompClub> CompClubs { get; set; }
        public virtual DbSet<CompDate> CompDates { get; set; }
        public virtual DbSet<CompDiamond> CompDiamonds { get; set; }
        public virtual DbSet<CompDiamondAllocation> CompDiamondAllocations { get; set; }
        public virtual DbSet<CompDivision> CompDivisions { get; set; }
        public virtual DbSet<CompFixture> CompFixtures { get; set; }
        public virtual DbSet<CompFixtureTemplate> CompFixtureTemplates { get; set; }
        public virtual DbSet<CompGroup> CompGroups { get; set; }
        public virtual DbSet<CompTeam> CompTeams { get; set; }
        public virtual DbSet<CompTimeSlot> CompTimeSlots { get; set; }
        public virtual DbSet<CompType> CompTypes { get; set; }
        public virtual DbSet<CompUmpireAllocation> CompUmpireAllocations { get; set; }
        public virtual DbSet<BasicLadder> BasicLadders { get; set; }
        public virtual DbSet<ClubContactView> ClubContactViews { get; set; }
        public virtual DbSet<FullLadder> FullLadders { get; set; }
        public virtual DbSet<TeamLadderAndGame> TeamLadderAndGames { get; set; }
        public virtual DbSet<TeamLadderAndGames_Crosstab> TeamLadderAndGames_Crosstab { get; set; }
        public virtual DbSet<ScoreSlip> ScoreSlips { get; set; }
    }
}
