//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreSlip
    {
        public int TimeSlot { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int Diamond { get; set; }
        public string Grade { get; set; }
        public string Division { get; set; }
        public string DisplayName { get; set; }
        public int Game { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string MatchCode { get; set; }
        public int CompID { get; set; }
    }
}
